name: Deploy

on:
  push:
    branches:
      - main

env:
  - SERVER_HOST: 95.163.236.53
  - SERVER_USER: root
  - SERVER_PATH_BACKEND: /app/github-actions-practice/backend
  - SERVER_PATH_FRONTEND: /app/github-actions-practice/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_REG_RU }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - 
        name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      - 
        name: Deploy backend
        run: rsync --archive --compress --progress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH_BACKEND }}
      - 
        name: Deploy frontend
        run: rsync --archive --compress --progress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH_FRONTEND }}
